# Generated by Django 5.2.14 on 2026-05-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('duracao_minutos', models.FloatField()),
                ('total_registros', models.IntegerField()),
                ('postura_predominante', models.CharField(max_length=30)),
                ('score_postura_medio', models.FloatField()),
                ('piscadas_por_minuto', models.FloatField()),
                ('emocao_predominante', models.CharField(max_length=20)),
                ('score_ward', models.FloatField()),
                ('classificacao_ward', models.CharField(max_length=20)),
                ('resumo', models.TextField()),
                ('analise_postura', models.TextField()),
                ('analise_piscadas', models.TextField()),
                ('analise_emocao', models.TextField()),
                ('recomendacao_1', models.TextField()),
                ('recomendacao_2', models.TextField(blank=True, null=True)),
                ('recomendacao_3', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sessão Ward',
                'verbose_name_plural': 'Sessões Ward',
                'ordering': ['-data_hora'],
            },
        ),
    ]
